### ISSUE TITLE
`bytes` use results in C# code that won't compile

### ISSUE THREAD

**Issue by AArnott** [NordSecurity/uniffi-bindgen-cs#57]
After the `bytes` data type support was added [here](https://github.com/NordSecurity/uniffi-bindgen-cs/issues/26#issuecomment-1810585167), I upgraded to the new version, which worked. But when [I switched my `sequence<u8>` types to `bytes`](https://github.com/nerdcash/Nerdbank.Cryptocurrencies/compare/main...uniffi_bytes), the C# code stopped compiling.

> LightWallet.cs(814,24,814,41): error CS0103: The name 'FfiConverterUInt8' does not exist in the current context

Why is `FfiConverterUInt8` referenced but not generated?

**Comment by arg0d** [comment]
Try using `v0.7.0+v0.25.0`, should be fixed.

I think there is confusion here about the latest version. I haven't created Github Release, because I prefer to write changes in CHANGELOG.md, and creating Github Releases manually is a chore requiring to copy-paste changelog. To avoid confusion about latest version, do you think its OK to delete existing Github Releases (CHANGELOG.md and Git tags would remain ofcourse).

**Comment by arg0d** [comment]
If its the same with `v0.7.0+v0.25.0` then it sounds like a different issue from what I fixed. Try cleaning and rebuilding. If its really not fixed, then please post a minimal UDL example that reproduces an issue (no need for Rust code I think).

Deleting all existing releases is what I meant. Could you share your GH actions code for automating the releases?

**Comment by AArnott** [comment]
Ah, silly me. I forgot to run the `cargo install` again for the new version of the tool.

**Comment by AArnott** [comment]
Most of my github release publishing happens from Azure Pipelines, actually. But if you want to automate it from GitHub Actions, there seems to be [a plethora of options](https://github.com/marketplace?category=&type=actions&verification=&query=github+release).
